apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: devops
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
