name: Build, Push and Deploy to EKS

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      short_sha: ${{ steps.vars_step.outputs.SHORT_SHA }}
      full_image: ${{ steps.build_push_step.outputs.FULL_IMAGE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract short SHA
      id: vars_step
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build & Push Docker Image
      id: build_push_step
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        SHORT_SHA: ${{ steps.vars_step.outputs.SHORT_SHA }}
      run: |
        IMAGE="$REGISTRY/$REPOSITORY:$SHORT_SHA"

        # Build image
        docker build -t "$IMAGE" .

        # Push
        docker push "$IMAGE"

        echo "FULL_IMAGE=$IMAGE" >> $GITHUB_OUTPUT
        echo "Pushed $IMAGE"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ${{ vars.AWS_REGION }} \
          --name ${{ vars.EKS_CLUSTER_NAME }}

    - name: Inject image name into manifest
      env:
        FULL_IMAGE: ${{ needs.build-and-push.outputs.full_image }}
      run: |
        echo "Using image: $FULL_IMAGE"
        sed -i "s|IMAGE_NAME|$FULL_IMAGE|g" k8s/deployment.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
