name: Build, Push and Deploy to EKS

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      short_sha: ${{ steps.vars_step.outputs.SHORT_SHA }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract short SHA
      id: vars_step
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build & Push Docker Image
      env:
        SHORT_SHA: ${{ steps.vars_step.outputs.SHORT_SHA }}
      run: |
        docker build -t ${{ vars.ECR_REPOSITORY }} .
        docker tag ${{ vars.ECR_REPOSITORY }}:latest ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:$SHORT_SHA
        docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:$SHORT_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      SHORT_SHA: ${{ needs.build-and-push.outputs.short_sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Update kubeconfig
      run: |+
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME
          
    - name: Inject image version into deployment manifest
      run: |
        sed -i "s|IMAGE_TAG|$SHORT_SHA|g" k8s/deployment.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for rollout
      run: |
        kubectl rollout status deployment/devops-app -n devops
